services:
  pipeline_db:
    image: postgres:15-alpine
    container_name: ct-pipeline-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - pipeline-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  etl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ct-etl-pipeline
    depends_on:
      pipeline_db:
        condition: service_healthy
    environment:
      DB_HOST: pipeline_db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      SHARD_STORAGE_DIR: ${SHARD_STORAGE_DIR}
      COMPACTED_STORAGE_DIR: ${COMPACTED_STORAGE_DIR}
      STATE_MGT_DIR: ${STATE_MGT_DIR}
      PYTHONUNBUFFERED: 1
    volumes:
      - ./netflix_titles.csv:/app/data/netflix_titles.csv:ro
    networks:
      - pipeline-network
    restart: "no"

  dbt:
    build:
      context: .
      dockerfile: Dockerfile.dbt
    container_name: clinical_trials_dbt
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./dbt:/app/dbt
    command: dbt run --project-dir /app/dbt
networks:
  pipeline-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local