FROM python:3.12-alpine

WORKDIR /app

RUN apk add --no-cache dcron && \
    pip install --no-cache-dir dbt-core dbt-postgres

COPY dbt_studies /app/dbt_studies

RUN mkdir -p /var/log && chmod -R 777 /var/log

CMD ["dbt", "run", "--project-dir", "/app/dbt_studies"]