version: 2

models:
  - name: fact_study_condition
    columns:
      - name: study_condition_key
        tests:
          - unique
          - not_null

      - name: study_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_studies')
              field: study_key

      - name: condition_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_conditions')
              field: condition_key

      - name: etl_created_at
        tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - study_key
            - condition_key

  - name: fact_study_intervention
    columns:
      - name: study_intervention_key
        tests:
          - unique
          - not_null

      - name: study_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_studies')
              field: study_key

      - name: intervention_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_interventions')
              field: intervention_key

      - name: etl_created_at
        tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - study_key
            - intervention_key

  - name: fact_study_site
    columns:
      - name: study_site_key
        tests:
          - unique
          - not_null

      - name: study_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_studies')
              field: study_key

      - name: site_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_sites')
              field: site_key

      - name: etl_created_at
        tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - study_key
            - site_key

  - name: fact_study_sponsor
    columns:
      - name: study_sponsor_key
        tests:
          - unique
          - not_null

      - name: study_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_studies')
              field: study_key

      - name: sponsor_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_sponsors')
              field: sponsor_key

      - name: is_lead
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

      - name: is_collaborator
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

      - name: etl_created_at
        tests:
          - not_null
